#!/bin/sh -e

export CGO_CFLAGS="-I/home/dai/h2/maa_h2sdk_android/jni/nghttpx/nghttp2-1.6.0/lib/includes -I/home/dai/h2/maa_h2sdk_android/jni/nghttpx/nghttp2-1.6.0/lib/includes"
export CGO_LDFLAGS="-L/home/dai/h2/maa_h2sdk_android/jni/nghttpx/nghttp2-1.6.0/lib/.libs"
export LD_LIBRARY_PATH="/home/dai/h2/maa_h2sdk_android/jni/nghttpx/nghttp2-1.6.0/lib/.libs"
"$@"
